<link href="./public/css/datepicker.css" rel="stylesheet"/>
<link href="./public/css/doc.css" rel="stylesheet">
<link href="./public/css/timepicker.css" rel="stylesheet">
<h1 class="page-title">
    <i class="icon-home"></i>
    Agenda
</h1>
<div class="row-fluid">
    <span class="span12">
        <iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;hl=pt_BR&amp;bgcolor=%23cccccc&amp;src=linc.ufpa%40gmail.com&amp;color=%232F6309&amp;ctz=America%2FBelem" style=" border:solid 1px #777 " width="800" height="600" frameborder="0" scrolling="no"></iframe>
    </span>
    <!--    <div class="span5" style="border: 0px solid #000">
            <h1 class="year"></h1>
            <h2 class="time"></h2>
            <h3 class="month"></h3>
            <table id="calendar" class="calendar" style="width: 100%;border: 0px solid #000">
                <thead>
                </thead>
                <tbody>
                </tbody>
            </table>
            <hr/>
            <div align="center">
                <button name="last" id="last"  class="btn"><i class="icon-arrow-left"></i></button>
                <button name="current" id="current" value="Current" class="btn">Atual</button>
                <button name="next" id="next" class="btn"><i class="icon-arrow-right"></i></button>
            </div>
        </div>
        <div class="span7">
                    <div class="widget widget-table">
                        <div class="widget-header">
                            <i class="icon-th-list"/>
                            <h3>Table</h3>
                        </div>
                        <div class="widget-content">
                            <span>
                                Nenhum compromisso para hoje! 
                                <br/><a href="javascript:;">Ver Todos</a>
                            </span>
                        </div>
                    </div>
            <div class="widget-content well" style="margin-top: 25px;">
                <div class="navbar navbar-heading">
                    <div class="navbar-inner">
                        <div class="container" style="width: auto;">
                            <a class="brand" href="#">Compromissos</a> 
                            <a class="btn btn-warning pull-right" 
                               data-toggle="modal" href="#agendadialog"
                               style="color: black"><i class="icon-plus-sign"></i>&nbsp;Novo</a>
                        </div>
                    </div>
                </div>
                <div>
                    <div class="accordion" id="accordion2">
                        <div class="accordion-group">
                            <div class="accordion-heading">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse1">
                                    <span class="label label-warning pull-right"> <i class="icon-warning-sign"></i></span>
                                    Compromisso 1
                                </a>
                            </div>
                            <div id="collapse1" class="accordion-body collapse in">
                                <div class="accordion-inner">
                                    Detalhes do Compromisso 1
                                </div>
                            </div>
                        </div>
                        <div class="accordion-group">
                            <div class="accordion-heading">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse2">
                                    Compromisso 2
                                </a>
                            </div>
                            <div id="collapse2" class="accordion-body collapse">
                                <div class="accordion-inner">
                                    Detalhes do Compromisso 2
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>-->
</div>


<div id="agendadialog" class="modal hide fade " style="width: 30%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>Inserir Nova Compromisso</h3>
    </div>
    <form id="agendaform" onsubmit="inseriragenda(event)">

        <link href="./css/datepicker.css" rel="stylesheet"/>
        <div class="modal-body" >
            <div id="erroagenda" class="alert alert-danger" style="display: none;">
                <a class="close" onclick="$('#erroagenda').hide();">×</a>
                <span></span>
            </div>
            <div  class="row-fluid">
                <div class="span8">
                    Título:
                    <input style="width: 100%;" required="true" id="titulo">
                </div>
                <div class="span2">
                    Data:
                    <input style="width: 100%;" required="true" id="datainicio" >
                </div>
                <div class="span2">
                    Hora:
                    <input style="width: 100%;" class="timepicker" id="hora"/>
                </div>
                <div class="row-fluid">
                    <div class="span3">
                        Permissão
                        <select style="width: 100%" id="permissao">
                            <option>Público</option>
                            <option>Privado</option>
                        </select>
                    </div>
                    <div class="span5">
                        Destinatário
                        <input id="destinatario_nome" style="width: 100%"/>
                    </div>
                </div>
            </div>
            <div  class="row-fluid">
                <div class="span12">
                    Observações:
                    <textarea style="width: 100%" rows="4"></textarea>
                </div>
            </div>
        </div>
        <div class="modal-footer" >
            <button type="submit" class="btn btn-primary">Inserir</button>
            <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
        </div>
    </form>   
</div>


<!-- > -->
 <script>window.jQuery || document.write('<script src="./public/js/jquery-1.7.2.min.js"><\/script>');</script>
<!--<script src="./public/js/jquery-1.7.2.min.js"></script>-->
<script src="./public/js/bootstrap.js"></script>
<script src="./public/js/bootstrap/bootstrap-collapse.js"></script>
<script src="./public/js/ui.js"></script>
<script src="./public/js/bootstrap-datepicker.js"></script>
<script src="./public/js/bootstrap-timepicker.js"></script>
<script>
    $(document).ready(function(){
        try{
            $('#datainicio').datepicker({
                format: 'dd-mm-yyyy'
            });
        }catch(e){
        }
        try{
            $('.timepicker').timepicker();
        }catch(e){
        }
    });
    
    function inseriragenda(evento){
        
        evento.preventDefault();
    }
</script>