<style>
    .site-stats li {
        background-color:#F5F5F5;
        border-bottom-color:#DDDDDD;
        border-bottom-style:solid;
        border-bottom-width:1px;
        border-image:initial;
        border-left-color:#DDDDDD;
        border-left-style:solid;
        border-left-width:1px;
        border-right-color:#DDDDDD;
        border-right-style:solid;
        border-right-width:1px;
        border-top-color:#DDDDDD;
        border-top-style:solid;
        border-top-width:1px;
        cursor:pointer;
        margin-bottom:10px;
        margin-left:0;
        margin-right:0;
        margin-top:0;
        padding-bottom:10px;
        padding-left:20px;
        padding-right:20px;
        padding-top:13px;
        position:relative;
    }
    li {
        line-height:18px;
    }
    .site-stats {
        list-style-image:initial;
        list-style-position:initial;
        list-style-type:none;
    }
    ul {
        list-style-image:initial;
        list-style-position:initial;
        list-style-type:disc;
    }
</style>
<link href="./public/css/timeline.css" rel="stylesheet">
<h1 class="page-title">
    <i class="icon-home"></i>
    Dashboard
</h1>
<div class="stat-container">

    <div class="stat-holder">						
        <div class="stat">							
            <span>-</span>							
            Projetos Cadastrados							
        </div> <!-- /stat -->						
    </div> <!-- /stat-holder -->

    <div class="stat-holder">						
        <div class="stat">							
            <span>-</span>							
            Projetos Finalizados							
        </div> <!-- /stat -->						
    </div> <!-- /stat-holder -->

    <div class="stat-holder">						
        <div class="stat">							
            <span>-</span>							
            Pendências							
        </div> <!-- /stat -->						
    </div> <!-- /stat-holder -->

    <div class="stat-holder">						
        <div class="stat">							
            <span>-</span>							
            Usuários Cadastrados							
        </div> <!-- /stat -->						
    </div> <!-- /stat-holder -->

</div> <!-- /stat-container -->
<div class="row-fluid">
    <div class="span6">
        <div class=" widget widget-table">
            <div class="widget-header">
                <span class="icon">
                    <i class="icon-signal"></i>
                </span>
                <h3>Meus Grupos</h3>
            </div>
            <div class="widget-content">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <!--<td colspan="8" class="dataTables_empty" align="center">Carregando...</td>-->
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class=" widget widget-table">
            <div class="widget-header">
                <span class="icon">
                    <i class="icon-signal"></i>
                </span>
                <h3>Contatos</h3>
            </div>
            <div class="widget-content">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <!--<td colspan="8" class="dataTables_empty" align="center">Carregando...</td>-->
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="span6">
        <div class=" widget widget-table">
            <div class="widget-header">
                <i class="icon-th-large"></i>
                <h3>Atualizações</h3>
                <a class="btn pull-right" style="margin-top: 5px;margin-right: 5px;">Novo</a>
            </div>
            <div class="widget-content">
                <ol id="timeline">
                    <li> 
                        <div class="time">{{data}} Sept 16th, 2012 at 4:20 pm <span class="pull-right"><i class="icon-user"></i> <a href="#">Admin</a></span> </div>
                        <span class="corner"></span>
                        <p>
                            <!--Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido-->
                        </p>
                        <p class="time_bottom">
                            <span class="pull-left">
                                <i class="icon-comment"></i> <a href="javascript:;" name="viewcoment-1">3 Comments</a>
                                | <i class="icon-share"></i> <a href="#">39 Shares</a>
                            </span>
                        </p>
                        <div id="viewcoment-1" style="display: none">
                            <hr/>
                            <ol class="timeline_comment">
                                <li style="width:365px; -moz-border-radius:2px; border-radius:2px; webkit-border-radius:2px; border:0px solid #c3ccdf; padding:5px;">  
                                    <textarea style="width: 97.5%;"></textarea>
                                    <div align="right">
                                        <a class="btn btn-primary btn-mini">Enviar</a>
                                    </div>
                                </li>
                                <li style="width:373px; -moz-border-radius:2px;border:0px;border-top: 1px solid #E7EBF2; border-radius:2px; webkit-border-radius:2px;  padding:0px;">  
                                    <!--Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido-->
                                </li>
                            </ol>
                        </div>

                    </li>
                </ol> 
            </div>
        </div>
    </div>
</div>
<div id="postdialog" class="modal hide fade " style="width: 30%">
    <form id="formpost" >
        <div class="modal-body" >
            <div id="erropost" class="alert alert-danger" style="display: none;">
                <a class="close" onclick="$('#erropost').hide();">×</a>
                <span></span>
            </div>
        </div>
        <div class="modal-footer" >
            <button type="submit" class="btn btn-primary">Inserir</button>
            <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
        </div>
    </form>   
</div>
<script>
    window.Post = {
        $post:{},
        $posts:[],
    
        init:function(){
            $('a[name|=viewcoment]').each(function(){
                $(this).click(function(){
                    $("#"+$(this).attr('name')).toggle('slide')
                });
            });
            $('.example').tooltip({
                html:true,
                placement:'top',
                trigger:'hover',
                title:'Editar'
            });
        },
        inserir:function(){
        
        },
        updatelista:function(){
        
        },
        updatelistalocal:function(){
            
        }
    
    }
    
    $(document).ready(function(){
        Post.init();
    })
</script>