<link href="./public/css/guidely.css" rel="stylesheet"/>
<link href="./public/css/upload.css" rel="stylesheet"/>
<style>
    #dropArea:hover{
        background-color: lightgrey;
    }
</style>
<h1 class="page-title">
    <i class="icon-th-list"></i>
    Projetos
</h1>
<div id="btnstop">
    <div class="btn-group" data-toggle="buttons-radio" style="float: right">
        <button id="listabtnview" class="btn active view" view="lista" onclick="Projeto.goview($(this))">Listar Todos</button>
        <button id="formbtnview" class="btn view" view="form" onclick="Projeto.goview($(this))">Novo Projeto</button>
        <button id="orcamentobtnview" class="btn view" view="orcamento" onclick="Projeto.goview($(this))">Orçamentos</button>
    </div>
</div>
<br/>
<div id="lista" style="margin-top: -30px;">
    <div id="listaprojeto_">
        <h2>Todos os Projetos</h2>
        <hr/>
        <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" id="listaprojeto" style="margin-top: -2px;">
            <thead>
                <tr>
                    <th style="width: 10px;">ID</th>
                    <th>Projeto</th>
                    <th style="width:100px">Coordenador</th>
                    <th style="width:80px">Tipo Projeto</th>
                    <th style="width:80px">Período</th>
                    <td align="center" style="width: 30px;" ></td>
                    <td align="center" style="width: 30px;" ></td>
                    <td align="center" style="width: 30px;" ></td>
                    <td align="center" style="width: 30px;" ></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="8" class="dataTables_empty" align="center">Carregando...</td>
                </tr>
            </tbody>
        </table>
        <div id="msgerrogeral" class="alert alert-danger" style="display: none;margin-top: 5px;">
            <a class="close" onclick="$('#msgerrogeral').hide();">×</a>
            <span></span>
        </div>
        <a href="javascript:;" controller="index" action="configuracoes" onclick="Layout.go($(this))" class="btn pull-right">Configurações</a>
    </div>
    <div id="sobre" style="display:none">
        <h2 style="margin-top: -30px;">Informações do Projeto</h2>
        <hr/>
        <div id="detalheprojeto" class="row" style="margin-left:5%">

            <div class="row-fluid">
                <span class="span3">
                    <strong>Apelido:</strong>
                </span>
                <span class="span9">
                    <span >
                        {{apelido}}
                    </span>
                </span>
            </div>
            <div class="row-fluid">
                <span class="span3">
                    <strong>Título:</strong>
                </span>

                <span class="span9">
                    <span >
                        {{titulo}}
                    </span>
                </span>
            </div>
            <div class="row-fluid">
                <span class="span3">
                    <strong>Nº do Processo:</strong>
                </span>
                <span class="span9">
                    <span>
                        {{processo}}
                    </span>
                </span>
            </div>
            <div class="row-fluid">
                <span class="span3">
                    <strong>Edital:</strong>
                </span>
                <span class="span9">
                    <span>

                        {{edital}}
                    </span>
                </span>
            </div>

            <div class="row-fluid">
                <span class="span3">
                    <strong>Proponente:</strong>
                </span>
                <span class="span9">
                    <span>
                        {{apelido}}
                    </span>
                </span>
            </div>
            <div class="row-fluid">
                <span class="span3">
                    <strong>Financiador:</strong>
                </span>
                <span class="span9">
                    <span>
                        {{financiador}}
                    </span>
                </span>
            </div>
            <div class="row-fluid">
                <span class="span3">
                    <strong>Coordenador:</strong>
                </span>
                <span class="span9">
                    <span>
                        {{coordenador}}
                    </span>
                </span>
            </div>
            <div class="row-fluid">
                <span class="span3">
                    <strong>Coordenador Técnico:</strong>
                </span>
                <span class="span9">
                    <span>
                        {{coordenadortecnico}}
                    </span>
                </span>
            </div>
            <div class="row-fluid">
                <span class="span3">
                    <strong>Resumo:</strong>
                </span>
                <span class="span9">
                    <span>
                        {{resumo}}
                    </span>
                </span>
            </div>
            <div class="row-fluid">
                <span class="span3">
                    <strong>Período:</strong>
                </span>
                <span class="span9">
                    <span>
                        {{periodo}}
                    </span>
                </span>
            </div>
            <div class="row-fluid">
                <span class="span3">
                    <strong>Página do Projeto:</strong>
                </span>
                <span class="span9">
                    <span>
                        {{url}}
                    </span>
                </span>
            </div>
            <hr/>
            <a class="btn" view="sobre" onclick="Projeto.hidedetalhes($(this));"><i class="icon-backward" style="margin-right: 5px;"></i>Voltar</a>
        </div>
    </div>
    <div id="orcamentoprojeto" style="display:none">
        <h2 style="margin-top: -30px;">Orçamento do Projeto</h2>
        <hr/>
        <div id="orcamentoprojetodetalhe" style="font-size: 14px;" >
            <div class="row-fluid">
                <span class="span3"><b>Plano de Trabalho:</b></span>
                <span class="span8">{{planotrabalho}}</span>
            </div>
            <div class="row-fluid">
                <span class="span3"><b>Total gasto:</b></span>
                <span class="span8">{{despesas}}</span>
            </div>
            <div class="row-fluid">
                <span class="span3"><b>Total disponível:</b></span>
                <span class="span8">{{disponivel}}</span>
            </div>
        </div>
        <a class="btn pull-right" style="margin-top: -20px;" onclick="Despesa.addview();">Nova Despesa</a>
        <hr/>
        <div id="despesageral_">
            <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-condensed" id="listadespesasgeral" style="margin-top: -30px;">
                <thead>
                    <tr>
                        <th>Rubrica</th>
                        <th>Valor Total</th>
                        <th>Gasto</th>
                        <th>Disponível</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="8" class="dataTables_empty" align="center">Carregando...</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="despesadetalhada_" style="display: none">
            <a class="btn" onclick="$('#despesadetalhada_').hide(0,function(){$('#despesageral_').show(0)});" style="margin-bottom: 10px;"><i class="icon-backward" ></i>&nbsp; Ver lista geral</a>
            <table id="listadetalhada" cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" style="width: 100%;">
                <tbody>
                    <tr>
                        <td colspan="4" class="dataTables_empty" align="center">Carregando...</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <hr/>
        <a href="javascript:;" class="btn pull-right">Extrato Detalhado</a>
        <div id="detalhardespesa" style="display: none">
            <h4>{{rubrica}}</h4>
            <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-condensed" id="listadespesasdetalhe" style="margin-top: -2px;">
                <thead>
                    <tr>
                        {{#colunas}}
                        <th>{{coluna}}</th>
                        {{/colunas}}
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="8" class="dataTables_empty" align="center">Carregando...</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <a class="btn" view="orcamentoprojeto" onclick="Projeto.hidedetalhes($(this));"><i class="icon-backward" style="margin-right: 5px;"></i>Voltar</a>
    </div>
</div>
<div id="form" style="display: none">
    <h2 style="margin-top: -30px;">Cadastrar Novo Projeto</h2>
    <hr/>
    <div  align="right">
        <div style="float: left;margin-right: 30px;width:200px;">
            <a href="#">
                <div  class="guidely-number"  style="display: block; width: 45px;float: left;margin-top: -8px">
                    <span>1</span>
                </div>
                <h3 id="guia1" class="guia" style="float: left;font-size: 1.1em;" >Informações Gerais</h3>
            </a>
        </div>
        <div style="float: left;margin-right: 30px;width:225px;">
            <div  class="guidely-number"  style="display: block; width: 45px;float: left;margin-top: -8px">
                <span>2</span>
            </div>
            <h3 id="guia2" class="guia" style="float: left;color: lightgray;font-size: 1.1em;"  >Detalhes do Projeto</h3>
        </div>
        <div style="float: left;margin-right: 30px;width:160px;">
            <div  class="guidely-number "  style="display: block; width: 45px;float: left;margin-top: -8px">
                <span>3</span>
            </div>
            <h3 id="guia3" class="guia" style="float: left;color: lightgray;font-size: 1.1em;"  >Orçamento</h3>
        </div>

        <div style="float: left;">
            <div  class="guidely-number "  style="display: block; width: 45px;float: left;margin-top: -8px">
                <span>4</span>
            </div>
            <h3 id="guia4" class="guia" style="float: left;color: lightgray;font-size: 1.1em;">Documentos</h3>
        </div>
    </div>
    <br/>
    <br/>
    <br/>
    <form id="form_step1" class="row-fluid form_step" style="margin-top: -25px;">
        <div class="span12">Título<textarea   id="titulo" name="titulo"rows="2" req="true" style="width: 100%;">{{titulo}}</textarea>
        </div>
        <div class="span12" style="margin-left: -1px;">Resumo<textarea  id="resumo" req="true"  rows="5" name="resumo" style="width: 100%;"  placeholder="Resumo do projeto" rel="popover" data-content="Entre com o Resumo do Projeto" data-original-title="Resumo">{{resumo}}</textarea>
        </div>
        <div class="span4" style="margin-left: -1px;">Apelido:<input id="apelido" name="apelido" req="true" style="width: 100%;" placeholder="Apelido do Projeto" rel="popover" data-content="Entre com o apelido do projeto" data-original-title="Apelido" value="{{apelido}}"/></div>
        <div class="span3" >
            Coordenador:
            <input  id="coordenador" name="coordenador" req="true" data-provide="typeahead" placeholder="Coordenador" style="width: 100%" value="{{coordenador}}"   />    
        </div>
        <div class="span2" >
            Data Inicio:
            <input type="text" value="{{inicio}}" id="inicio" req="true"  mask="99/99/9999" validator="date" placeholder="Data início" style="width: 100%" />
        </div> 
        <div class="span2">
            Data Término:
            <input type="text"  value="{{termino}}" id="termino" req="true" mask="99/99/9999" validator="date" placeholder="Data termino" style="width: 100%" />
        </div> 
    </form>
    <form id="form_step2" class="row-fluid" style="margin-top: 0px;display: none">
        <div class="span2">
            Tipo de Projeto
            <select id="tipoprojeto" class="input-small shadow_slect"> 
                <option val="-">Selecione</option>
                <option val="Pesquisa">Pesquisa</option>
                <option val="Desenvolvimento">Desenvolvimento</option>
                <option val="Extensão">Extensão</option>
            </select>
        </div> 
        <div class="span2"  style="width: 120px; margin-left: -1px;">Instituição <div style="width: 100%"><select class="input-small shadow_slect" style="width: 100%" id="proponente" > </select></div></div> 
        <div class="span2" style="width: 120px;">
            Financiador
            <div style="width: 100%">
                <select class="input-small shadow_slect" style="width: 100%" id="financiador" > 
                </select>
            </div>
        </div> 
        <div class="span3 ">
            Coordenador Técnico:
            <input  id="coordenadortecnicos" value="{{coordenador_tecnico}}" name="coordenadortecnicos" req="true" data-provide="typeahead" placeholder="Coordenador Tecnico" style="width: 90%"   />    
        </div> 
        <div class="span2" >Processo:<input id="processo" value="{{processo}}" name="processo"   style="width: 100%;" placeholder="ex. XXXXX/20XX" rel="popover" data-content="Entre com o número do Processo" data-original-title="Processo" /></div>
        <div class="span2" style="margin-left: -1px">Edital:<input id="edital" name="edital" req="true"  style="width: 100%;" value="{{edital}}"  placeholder="Edital" rel="popover" data-content="Entre com o Edital" data-original-title="Edital" /></div>
        <div class="span3">
            Url:
            <input id="url" value="{{url}}" name="url" style="width: 90%;" placeholder="Página do projeto" rel="popover" data-content="Entre com a página do Projeto" data-original-title="Página do Projeto" />
        </div>   
    </form>
    <form  id="form_step3" class="row-fluid" style="margin-top: 0px;display: none">

        <div class="row-fluid">

            <span class="span5">
                <h4  >

                    <a class="btn btn-warning" href="#" onclick="PlanoTrabalho.show()"
                       style="color: black"><i class="icon-plus-sign"></i></a>&nbsp;Plano de Trabalho
                </h4>

            </span>
            <span class="span6">
                Valor Total: <input id="valor" disabled="true" value="{{valor}}" style="width:40%;font-weight:bold" />
            </span>
        </div>


        <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" id="listaplanotrabalho" style="margin-top: -5px;width: 60%;margin-left: 15%">
            <thead>
                <tr>
                    <th>Rubrica</th>
                    <th>Valor</th>
                    <td align="center" style="width: 30px;" ></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="4" class="dataTables_empty" align="center">Carregando...</td>
                </tr>
            </tbody>
        </table>

        <h4><a class="btn btn-warning" style="color: black" href="#" onclick="Repasse.show()"><i class="icon-plus-sign"></i></a>&nbsp;Repasses</h4>
        <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" id="listarepasses" style="margin-top: -2px;width: 60%;margin-left: 15%">
            <thead>
                <tr>
                    <th>Repasse</th>
                    <th>Valor</th>
                    <td align="center" style="width: 30px;" ></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="4" class="dataTables_empty" align="center">Carregando...</td>
                </tr>
            </tbody>
        </table>
    </form>
    <form  id="form_step4" class="row-fluid" style="margin-top: 0px;display: none">

        <div id="dropArea" class="row-fluid well">
            <p style="font-size:18px;color:darkgray;margin-top: 20px;">Arraste aqui os arquivos que deseja anexar ao projeto.</p>
        </div>
        <!--        <div class="row-fluid">
                    Arquivos: <span id="count">0</span>
                    <br/>-->
        <canvas id="prog" width="500" height="20"></canvas>
        <!--                </div>-->
        <div class="row-fluid" style=" margin: 20px;width: 55.5%;">
            <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-condensed" id="listafiles" style="width: 100%">
                <thead>
                    <tr>
                        <th>Arquivos</th>
                        <th style="width: 10px;"></th>
                        <td align="center" style="width: 30px;" ></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="4" class="dataTables_empty" align="center">Carregando...</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="result" style="display: none"></div>
    </form>
    <hr/>
    <div id="btns_inserir" class="row-fluid">
        <div class="btn-group">
            <a id="btnback"  style="display: none;color: black" class="btn btn-warning span1" onclick="Projeto.backsteps();" ><i class="icon-backward" style="margin-right: 5px;"></i>Voltar</a>
            <a id="btnnext"  style="color: black" class="btn btn-warning span1" onclick="Projeto.nextsteps()" >Avançar<i class="icon-forward" style="margin-left: 5px;"></i></a>
            <a id="btnfinish" class="btn btn-primary span1" style="display: none" onclick="Projeto.inserir()" >Finalizar<i class="icon-ok-sign" style="margin-left: 5px;"></i>
            </a>
        </div>
    </div>
    <div id="processando" class="alert alert-info" style="display: none">
        <span>Processando...</span>
    </div>
    <div id="msgerro_inserir" class="alert alert-danger" style="display: none;margin-top: 5px;">
        <a class="close" onclick="$('#msgerro_inserir').hide();">×</a>
        <span></span>
    </div>
</div>

<div id="orcamento" style="display: none;">
    <h2 style="margin-top: -30px;">Orçamento Geral</h2>
    <hr/>
    <div class="row" style="margin-left:10%;display: none" >
        <div class="row-fluid">
            <span class="span3">
                <h4>Plano de Trabalho Geral :</h4>
            </span>
            <span class="span9">
                <strong>{{planotrabalho}}</strong>
            </span>
        </div>
        <div class="row-fluid">
            <span class="span3">
                <h4>Total Gasto :</h4>
            </span>
            <span class="span9">
                <strong>{{despesas}}</strong>
            </span>
        </div>
        <div class="row-fluid">
            <span class="span3">
                <h4>Total Disponível :</h4>
            </span>
            <span class="span9">
                <strong>{{disponivel}}</strong>
            </span>
        </div>
    </div>
</div>
<hr/>
<div id="planotrabalho" class="modal hide fade " style="width: 30%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>Inserir Nova Rubrica no Plano de Trabalho</h3>
    </div>
    <form id="formplanotrabalho" onsubmit="PlanoTrabalho.inserir(event)">

        <div class="modal-body" >
            <div id="erroplanotrabalho" class="alert alert-danger" style="display: none;">
                <a class="close" onclick="$('#erroplanotrabalho').hide();">×</a>
                <span></span>
            </div>
            <div  class="row-fluid">
                <div class="span4" >
                    Rubrica
                    <div style="width: 90%">
                        <select id="rubrica" class="input-small shadow_slect" style="width: 90%">
                        </select>
                    </div>
                </div>
                <div class="span4">
                    Valor
                    <input id="valorrubrica" validator="money" style="width: 100%"/>
                </div>
            </div>

        </div>
        <div class="modal-footer" >
            <button type="submit" class="btn btn-primary">Inserir</button>
            <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
        </div>
    </form>   
</div>
<div id="repasses" class="modal hide fade " style="width: 40%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>Inserir Novo Repasse</h3>
    </div>
    <form id="formrepasses" onsubmit="Repasse.inserir(event)">
        <div class="modal-body" >
            <div id="errorepasses" class="alert alert-danger" style="display: none;">
                <a class="close" onclick="$('#erroplanotrabalho').hide();">×</a>
                <span></span>
            </div>
            <div class="row-fluid">
                <div class="span4">
                    Data do Repasse:
                    <input id="datarepasse"  mask="99/99/9999" validator="date" style="width: 70%"/>
                </div>
                <div class="span4">
                    Valor
                    <input id="valorrepasse" style="width: 90%" validator="money"/>
                </div>
            </div>
        </div>
        <div class="modal-footer" >
            <button type="submit" class="btn btn-primary">Inserir</button>
            <a href="#" class="btn" onclick="Repasse.lista();" data-dismiss="modal">Cancelar</a>
        </div>    
    </form>
</div>
<div id="despesadialog" class="modal hide fade " style="width: 30%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>Nova Despesa</h3>
    </div>
    <form id="formdespesa" onsubmit="Despesa.add(event)">
        <div class="modal-body">
            <div id="formdespesa_step1" class="row-fluid">
                <div class="span4">
                    Rubrica
                    <select id="tiporubrica">

                    </select>
                </div>
            </div>
            <div id="formdespesa_step2">

            </div>
        </div>
        <div class="modal-footer" >
            <button type="submit" class="btn btn-primary">Inserir</button>
            <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
        </div>    
    </form>
</div>
<script async>

    var Util = {
        float2moeda:function(num) {
            var x = 0;
            if(num<0){
                num = Math.abs(num);
                x = 1;
            }
            if(isNaN(num)) num = "0";
            var cents = Math.floor((num*100+0.5)%100);
            num = Math.floor((num*100+0.5)/100).toString();
            if(cents < 10) cents = "0" + cents;
            for (var i = 0; i < Math.floor((num.length-(1+i))/3); i++)
                num = num.substring(0,num.length-(4*i+3))+'.'+num.substring(num.length-(4*i+3));
            var ret = num + ',' + cents;
            if (x == 1) ret = ' - ' + ret;
            return ret;
        }
    };
    
    var Repasse = {
        $lista:null,
        $erromsg:$("#erroplanotrabalho"),
        $input_datarepasse :$("#datarepasse"),
        $input_valorrepasse :$("#valorrepasse"),
        $modal:$("#repasses"),
        
        limpar:function(){
            try{
                Repasse.$input_datarepasse.val('');
                Repasse.$input_valorrepasse.val('');
                Repasse.$erromsg.hide();
                Repasse.$input_datarepasse.removeClass('alert-danger');
                Repasse.$input_valorrepasse.removeClass('alert-danger');
            }catch(e){
                console.log(e);
            }  
        },
        inserir:function(evento){
            try{
                Repasse.$erromsg.hide();
                var datarepasse = Repasse.$input_datarepasse.val();
                var valorrepasse = Repasse.$input_valorrepasse.val();
                if(!Repasse.$input_datarepasse.hasClass('alert-danger')){
                    if(datarepasse!=""&&valorrepasse!=""){
                        var _Data = Repasse.$lista.fnGetData();	
                        var existe = false;
                        for(var i=0; i<_Data.length;i++){
                            if(datarepasse==_Data[i].datarepasse){
                                var old = parseFloat(_Data[i].valorrepasse.replace(".","").replace(",","."));
                                valorrepasse = parseFloat(valorrepasse.replace(".","").replace(",","."));
                                valorrepasse = Util.float2moeda(old+valorrepasse);
                                Repasse.$lista.fnUpdate({'datarepasse':datarepasse,'valorrepasse':valorrepasse,'':null}, i);
                                existe = true;
                            }
                        }
                        if(!existe){
                            Repasse.$lista.fnAddData({'datarepasse':datarepasse,'valorrepasse':valorrepasse,'':null});
                        }
                        Repasse.limpar();
                        Repasse.atualizar();
                        Repasse.$modal.modal('hide');
                    }else{
                        Repasse.$erromsg.find("span").html("Ops! Ocorreu um erro<br/>A Data do repasse e seu valor são campos obrigatórios!");
                        Repasse.$erromsg.show('slide');
                    }
                }else{
                    Repasse.$erromsg.find("span").html("Ops! Ocorreu um erro<br/>Insira uma data válida para o repasse!");
                    Repasse.$erromsg.show('slide');
        
                }
            }catch(e){
                console.log(e);
            }
            evento.preventDefault();  
        },
        remover:function(row){
            Repasse.$lista.fnDeleteRow( row );
        },
        atualizar:function(){
            Repasse.$lista.fnDraw();
        },
        lista:function(){
            try{
                Repasse.$lista = $('#listarepasses').dataTable( {
                    "aaData": new Array(),
                    "aoColumns": [
                        { "mData": "datarepasse"},
                        { "mData": "valorrepasse"},
                        { "mData": null, "fnRender" : function(obj) {

                                var deletar ='<a  href="javascript:;" class="btn btn-danger" onclick="Repasse.remover('+obj.iDataRow+')"><i  class="icon-trash"></i></a>';
                                return deletar;
                            }
                        }
                    ],
                    "bPaginate":false,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bInfo": false,
                    "bAutoWidth": false,
                    "oLanguage": {
                        "sSearch": "Buscar:",
                        "sProcessing":"Processando...",
                        "sLoadingRecords":"Carregando...",
                        "sLengthMenu":"Mostrando _MENU_ registros",
                        "sInfoFiltered": "(Filtrado de _MAX_ registros)",
                        "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                        "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sZeroRecords":"Nenhum registro encontrado",
                        "oPaginate": {
                            "sFirst": "Primeira",
                            "sLast": "Última",
                            "sNext": "Próxima",
                            "sPrevious": "Anterior"
                        }
                    },
                    "bStateSave": true,
                    "bDestroy":true
                });
            }catch(e){
                console.log(e);
            }
        },
        show:function(){
            showmodal('repasses');
        }
    };
    
    var PlanoTrabalho = {
        $lista:null,
        $valor : $("input#valor"),
        $erromsg:$("#erroplanotrabalho"),
        $input_rubrica:$("#rubrica"),
        $input_valor:$("#valorrubrica"),
        $modal:$("#planotrabalho"),
        
        atualizarvalor:function(){
            var val=0;
            var _Data = PlanoTrabalho.$lista.fnGetData();
            for(var i=0; i<_Data.length;i++){
                val += parseFloat(_Data[i].valor.replace(".","").replace(",","."));
            }
            //console.log('1- '+PlanoTrabalho.$valor.val());
            $("input#valor").val(Util.float2moeda(val));
            //console.log('2- '+$("input#valor").val());
        },
        remover:function(row){
            PlanoTrabalho.$lista.fnDeleteRow(row);
            PlanoTrabalho.atualizarvalor();
        },
        atualizar:function(){
            PlanoTrabalho.$lista.fnDraw();  
        },
        lista:function(){
            try{
                PlanoTrabalho.$lista = $('#listaplanotrabalho').dataTable({
                    "aaData": new Array(),
                    "aoColumns": [
                        { "mData": "rubrica"},
                        { "mData": "valor"},
                        { "mData": null, "fnRender" : function(obj){
                                var deletar ='<a  href="javascript:;" class="btn btn-danger" onclick="PlanoTrabalho.remover('+obj.iDataRow+')"><i class="icon-trash"></i></a>';
                                return deletar;
                            }
                        }
                    ],
                    "bPaginate":false,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bInfo": false,
                    "bAutoWidth": false,
                    "oLanguage": {
                        "sSearch": "Buscar:",
                        "sProcessing":"Processando...",
                        "sLoadingRecords":"Carregando...",
                        "sLengthMenu":"Mostrando _MENU_ registros",
                        "sInfoFiltered": "(Filtrado de _MAX_ registros)",
                        "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                        "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sZeroRecords":"Nenhum registro encontrado",
                        "oPaginate": {
                            "sFirst": "Primeira",
                            "sLast": "Última",
                            "sNext": "Próxima",
                            "sPrevious": "Anterior"
                        }
                    },
                    "bStateSave": true,
                    "bDestroy":true
                } );    
            }catch(e){
                console.log(e);
            }
        },
        inserir:function(evento){
            PlanoTrabalho.$erromsg.hide();
            var rubrica_ = PlanoTrabalho.$input_rubrica.val();
            var valor_ = PlanoTrabalho.$input_valor.val();
        
            if(rubrica_!=""&&valor_!=""){
                try{
                    var _Data = PlanoTrabalho.$lista.fnGetData();	
                    var existe = false;

                    for(var i=0; i<_Data.length;i++){
                        if(rubrica_==_Data[i].rubrica){
                            var old = parseFloat(_Data[i].valor.replace(".","").replace(",","."));
                            valor_ = parseFloat(valor_.replace(".","").replace(",","."));
                            valor_ = Util.float2moeda(old+valor_);
                            PlanoTrabalho.$lista.fnUpdate({'rubrica':rubrica_,'valor':valor_,'':null}, i);
                            existe = true;
                        }
                    }
                    if(!existe){
                        PlanoTrabalho.$lista.fnAddData({'rubrica':rubrica_,'valor':valor_,'':null});
                    }
                
                    PlanoTrabalho.atualizarvalor();
                    //console.log(.length);
                }catch(e){
                    console.log(e);
                }	

                PlanoTrabalho.$input_rubrica.val('');
                PlanoTrabalho.$input_valor.val('');
                PlanoTrabalho.atualizar();
                PlanoTrabalho.$modal.modal('hide');
            }else{
                PlanoTrabalho.$erromsg.find("span").html("Ops! Ocorreu um erro<br/>A rubrica e o valor são campos obrigatórios!");
                PlanoTrabalho.$erromsg.show('slide');
            }
            evento.preventDefault();
        },
        show:function(){
            showmodal('planotrabalho');
        }
    };
    
    var Projeto = {
        $projeto:{},
        $listaprojeto:null,
        $listaview:$("#listaprojeto_"),
        $sobreview:$("#sobre"),
        $orcamentoview:$("#orcamentoprojeto"),
        $detalheview:$("#detalheprojeto"),
        $droparea : $("#dropArea"),
        $orcamentogeral:$('#orcamento'),
        $orcamentogeraltemplate:null,
        //form
        $form_step1: $('#form_step1'),
        $form_step2: $('#form_step2'),
        $form_step3: $('#form_step3'),
        $form_step4: $('#form_step4'),
        $formplanotrabalho: $('#formplanotrabalho'),
        $formrepasses: $('#formrepasses'),
        $btnback: $("#btnback"),
        $btnnext: $("#btnnext"),
        $btnfinish: $("#btnfinish"),
        $btnsinserir:$("#btns_inserir"),
        $back:0,
        $current:1,
        $next:2,
        $guia:$(".guia"),
        $select_tipoprojeto: $('select#tipoprojeto'),
        //end form
        $detalhetemplate:null,
        $orcamentotemplate:null,
        $edit:false,
        $msgerro:$("#msgerro_inserir"),
        $msgerrogeral:$("#msgerrogeral"),
        $msgprocessando:$("#processando"),
        
        editview:function(row){
            try{
                Projeto.$edit = true;
                Projeto.$projeto = Projeto.$listaprojeto.fnGetData()[row];
                console.log(Projeto.$projeto);
                //
                var template = Projeto.$form_step1.html();
                var html = Mustache.to_html(template, Projeto.$projeto);
                Projeto.$form_step1.html(html);
                template = Projeto.$form_step2.html();
                html = Mustache.to_html(template, Projeto.$projeto);
                Projeto.$form_step2.html(html);
                template = Projeto.$form_step3.html();
                html = Mustache.to_html(template, Projeto.$projeto);
                Projeto.$form_step3.html(html);
                
                Projeto.goview($("#formbtnview"));
                
                $("select#tipoprojeto").val(Projeto.$projeto.tipoprojeto);
                $("select#financiador").val(Projeto.$projeto.financiador_idfinanciador);
                //                Projeto.$select_tipoprojeto.val(Projeto.$projeto.tipoprojeto);
                
                
                Projeto.resetform();
                Projeto.getorcamento();
                //resetformprojeto();	
            }catch(e){
                console.log(e);
            }
        },
        getorcamento:function(){
            try{
                $("input#valor").val(Projeto.$projeto.valor);
                $.getJSON('./index/getorcamento?projeto='+Projeto.$projeto.idprojeto,
                function(json){
                    console.log(json['repasses']);
                    Repasse.lista();
                    PlanoTrabalho.lista();
                    //
                    $.each(json['repasses'], function(key,value){
                        Repasse.$lista.fnAddData(value);
                    });
                    console.log(json['planotrabalho']);
                    $.each(json['planotrabalho'], function(key,value){
                        PlanoTrabalho.$lista.fnAddData(value);
                    });
                });
            }catch(e){
                console.log('getorcamento: '+e);
            }
        },
        deletar:function(idprojeto){
            $.ajax({
                type:'POST',
                data:{idprojeto:idprojeto},
                url:'./index/removerprojeto',
                dataType:'json',
                success: function(json){
                    if(json['status']=='sucesso'){
                        Projeto.listaprojeto();
                    }else{
                        Projeto.$msgerrogeral.find("span").html('Ops! Que feio... Ocorreu um erro ao processar sua requisição: '+json['msg']);
                    }
                }
            });
        },
        resetform:function(){
            Projeto.$back = 0;
            Projeto.$current = 1;
            Projeto.$next = 2;
            Projeto.$btnback.css("display",'none');
            Projeto.$btnfinish.css("display",'none');
            Projeto.$btnnext.css("display",'block');  
        },
        showorcamento:function(row){
            try{
                Projeto.$projeto = Projeto.$listaprojeto.fnGetData()[row];
                $.getJSON('./index/orcamentobyprojeto?total='+Projeto.$projeto.valor+'&idprojeto='+Projeto.$projeto.idprojeto,
                function(json){
                    Projeto.$listaview.hide(0,function(){
                        shortcut.add("Backspace", function() {
                            Projeto.$orcamentoview.hide(0,function(){
                                Projeto.$listaview.show(0,function(){
                                    Projeto.$listaprojeto.fnDraw();
                                    shortcut.remove("Backspace");
                                });
                            });
                        });
                        if(Projeto.$orcamentotemplate == null){
                            Projeto.$orcamentotemplate = $("#orcamentoprojetodetalhe").html();
                        }
                        var html = Mustache.to_html(Projeto.$orcamentotemplate, json);
                        $("#orcamentoprojetodetalhe").html(html);
                        Projeto.$orcamentoview.show(0,function(){
                            Despesa.listageral();
                        });
                    });
                });
            }catch(e){
                console.log(e);
            }
        },
        showdetalhes:function(row){
            try{
                Projeto.$projeto = Projeto.$listaprojeto.fnGetData()[row];
                Projeto.$listaview.hide(0,function(){
                    shortcut.add("Backspace", function() {
                        Projeto.$sobreview.hide(0,function(){
                            Projeto.$listaview.show(0,function(){
                                Projeto.$listaprojeto.fnDraw();
                                shortcut.remove("Backspace");
                            });
                        });});
                    if(Projeto.$detalhetemplate==null){
                        Projeto.$detalhetemplate = Projeto.$detalheview.html();
                    }
                    var html = Mustache.to_html(Projeto.$detalhetemplate, Projeto.$projeto);
                    Projeto.$detalheview.html(html);
                    Projeto.$sobreview.show();
                });

            }catch(e){
                console.log(e);
            }
        },
        hidedetalhes:function(btn){
            $("#"+btn.attr('view')).hide(0,function(){
                Projeto.$listaview.show(0,function(){
                    Projeto.$listaprojeto.fnDraw();
                    shortcut.remove("Backspace");
                });
            });
        },
        listaprojeto:function(){
            try{
                if(Projeto.$listaprojeto == null){
                    Projeto.$listaprojeto = $("#listaprojeto").dataTable({
                        "sPaginationType": "bootstrap",
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": "./index/projetolist",   
                        "aoColumns": [
                            { "mData": "idprojeto"},
                            { "mData": "apelido"},
                            { "mData": "coordenador"},
                            { "mData": "tipoprojeto"},
                            { "mData": null,"fnRender" : function(obj) {
                                    var inicio = obj.aData.inicio;
                                    var termino = obj.aData.termino;
                                    var value="";
                                    if(inicio != undefined && termino != undefined){
                                        value = inicio.split('-')[0]+'/'+termino.split('-')[0];
                                        obj.aData.inicio=inicio.split('-')[2]+'/'+inicio.split('-')[1]+'/'+inicio.split('-')[0];
                                        obj.aData.termino=termino.split('-')[2]+'/'+termino.split('-')[1]+'/'+termino.split('-')[0];
                                    }
                                    return value;
                                }
                            },
                            { "mData": null,"fnRender" : function(obj) {
                                    var idprojeto = obj.aData.idprojeto;
                                    var sobre ='<a  href="#" class="btn viewproject" onclick="Projeto.showdetalhes('+obj.iDataRow+');"><i  class="icon-eye-open"></i></a>';
                                    return sobre;
                                }
                            },
                            { "mData": null,"fnRender" : function(obj) {
                                    var idprojeto = obj.aData.idprojeto; 
                                    var orcamento ='<a  href="#" class="btn orcamentoproject" onclick="Projeto.showorcamento('+obj.iDataRow+');"><i  class="icon-money"></i></a>';
                                    return orcamento;
                                }
                            },
                            { "mData": null, "fnRender" : function(obj) {
                                    var editar ='<a  href="#" class="btn editproject " onclick="Projeto.editview('+obj.iDataRow+');"><i  class="icon-edit"></i></a>';
                                    return editar;
                                }
                            },
                            { "mData": null, "fnRender" : function(obj) {
                                    var idprojeto = obj.aData.idprojeto; 
                                    var deletar ='<a  href="#"class="btn btn-danger" onclick="Projeto.deletar('+idprojeto+');"><i  class="icon-trash"></i></a>';
                                    return deletar;
                                }
                            }
                        ],
                        "bPaginate":true,
                        "bLengthChange": false,
                        "bFilter": true,
                        "bInfo": true,
                        "bAutoWidth": false,
                        "oLanguage": {
                            "sSearch": "Buscar:",
                            "sProcessing":"Processando...",
                            "sLoadingRecords":"Carregando...",
                            "sLengthMenu":"Mostrando _MENU_ registros",
                            "sInfoFiltered": "(Filtrado de _MAX_ registros)",
                            "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                            "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                            "sEmptyTable": "Nenhum registro encontrado",
                            "sZeroRecords":"Nenhum registro encontrado",
                            "oPaginate": {
                                "sFirst": "Primeira",
                                "sLast": "Última",
                                "sNext": "Próxima",
                                "sPrevious": "Anterior"
                            }
                        },
                        "bStateSave": true,
                        "bDestroy":true
                    });
                }else{
                    Projeto.$listaprojeto.fnDraw();
                }
            }catch(e){
                console.log(e);
            }
            $('.viewproject').tooltip({
                html:true,
                placement:'top',
                trigger:'hover',
                title:'Visualizar Informações'
            });
            $('.orcamentoproject').tooltip({
                html:true,
                placement:'top',
                trigger:'hover',
                title:'Orçamento'
            });
            $('.editproject').tooltip({
                html:true,
                placement:'top',
                trigger:'hover',
                title:'Editar Projeto'
            });
        },
        nextsteps:function (){
            try{
                if(Projeto.validastep()){
                    $( "#form_step"+Projeto.$current).hide(0, function() {
                        $( "#form_step"+Projeto.$next).show();
                    });
                    Projeto.$back++;
                    Projeto.$current++;
                    Projeto.$next++;
                    //controle dos btns
                    if(Projeto.$back>0){
                        Projeto.$btnback.css("display","block");
                    }
                    //
                    if(Projeto.$current==4){
                        Projeto.$btnnext.css("display",'none');
                        Projeto.$btnfinish.css("display",'block');
                    }else{
                        Projeto.$btnnext.css("display",'block');
                        Projeto.$btnfinish.css("display",'none');
                    }
                    //controle dos steps
                    Projeto.$guia.each(function(){
                        $(this).css('color','lightgray');
                    });
                    $("#guia"+Projeto.$current).css('color','#FF9900');
                    addMaskAndValidator("form_step"+Projeto.$current);
                }
            }catch(e){
                console.log('nextsteps: '+e);
            }
        },
        backsteps:function(){
            try{
                $("#form_step"+Projeto.$current).hide(0, function() {
                    $( "#form_step"+Projeto.$back).show();
                });
                Projeto.$back--;
                Projeto.$current--;
                Projeto.$next--;
                if(Projeto.$back==0){
                    Projeto.$btnback.css("display","none");
                    Projeto.$btnnext.css("display",'block');
                }else{
                    Projeto.$btnback.css("display","block");
                    Projeto.$btnnext.css("display",'block');
                }
                if(Projeto.$current!=5){
                    Projeto.$btnfinish.css("display",'none');
                }
                //controle dos steps
                Projeto.$guia.each(function(){
                    $(this).css('color','lightgray');
                });
                $("#guia"+Projeto.$current).css('color','#FF9900');
                addMaskAndValidator("form_step"+Projeto.$current);
             
            }catch(e){
                console.log(e);
            }
        },
        validastep:function()
        {
            return validaForm("form_step"+Projeto.$current);
            //return 1;
        },
        atualizar:function(){
            try{
                //$("#btns_inserir").hide();
                Projeto.$msgerro.hide();
                Projeto.$msgprocessando.show('slide');
                //
                var dataString='';
                dataString+=readForm('form_step1');
                dataString+=readForm('form_step2');
                dataString+=readForm('form_step3');
                dataString+="&repasses="+JSON.stringify(Repasse.$lista.fnGetData());	
                dataString+="&planotrabalho="+JSON.stringify(PlanoTrabalho.$lista.fnGetData());	
                dataString+="&idprojeto="+Projeto.$projeto.idprojeto;
                console.log(dataString);
                $.ajax({
                    type:'POST',
                    data:dataString,
                    url:'./index/atualizarprojeto',
                    dataType:'json',
                    success: function(json){
                        if(json['status']=='sucesso'){
                            Projeto.$btnsinserir.show();
                            Projeto.$msgerro.hide('slide');
                            Projeto.$msgprocessando.hide();
                    
                            Repasse.$lista==null
                            PlanoTrabalho.$lista==null
                    
                            Projeto.goview($("#listabtnview"));
                        }else{
                            $("#msgerro_inserir span:first").html('Ops! Que feio, ocorreu um erro ao inserir: '+json['erro']);
                            Projeto.$btnsinserir.show();
                            Projeto.$msgprocessando.hide();
                            Projeto.$msgerro.show('slide');
                        }
                    }
                });
            }catch(e){
                console.log('atualizar : ' +e);  
            }
        },
        inserir:function(){
            try{
                if(Projeto.$edit){
                    Projeto.atualizar();
                }else{
                    //$("#btns_inserir").hide();
                    Projeto.$msgerro.hide();
                    Projeto.$msgprocessando.show('slide');
                    //
                    var dataString='';
                    dataString+=readForm('form_step1');
                    dataString+=readForm('form_step2');
                    dataString+=readForm('form_step3');
                    dataString+="&repasses="+JSON.stringify(Repasse.$lista.fnGetData());	
                    dataString+="&planotrabalho="+JSON.stringify(PlanoTrabalho.$lista.fnGetData());	
                    console.log(dataString);
                    $.ajax({
                        type:'POST',
                        data:dataString,
                        url:'./index/inserirprojeto',
                        dataType:'json',
                        success: function(json){
                            if(json['status']=='sucesso'){
                                Projeto.$btnsinserir.show();
                                Projeto.$msgerro.hide('slide');
                                Projeto.$msgprocessando.hide();
                    
                                Repasse.lista();
                                PlanoTrabalho.lista();
                    
                                Projeto.goview($("#listabtnview"));
                            }else{
                                $("#msgerro_inserir span:first").html('Ops! Que feio, ocorreu um erro ao inserir: '+json['erro']);
                                Projeto.$btnsinserir.show();
                                Projeto.$msgprocessando.hide();
                                Projeto.$msgerro.show('slide');
                            }
                        }
                    });
                }
            }catch(e){
                console.log('inserir : ' +e);  
            }
        },
        goview:function(btn){
            try{
                $('.view').each(function(){
                    $("#"+$(this).attr('view')).hide();
                    $(this).removeClass('active');
                });
                if(!Projeto.$edit){
                    clearFormObj(Projeto.$form_step1);
                    clearFormObj(Projeto.$form_step2);
                    clearFormObj(Projeto.$form_step3);
                    clearFormObj(Projeto.$form_step4);
                }
                $("#"+btn.attr('view')).show();
                btn.addClass('active');
                if(btn.attr('view')=='lista'){
                    Projeto.$edit = false;
                    Projeto.listaprojeto();
                }else if(btn.attr('view')=='form'){
                    Projeto.$form_step1.show();
                    Projeto.$form_step2.hide();
                    Projeto.$form_step3.hide();
                    Projeto.$form_step4.hide();
                
                    Projeto.$back= 0;
                    Projeto.$current = 1;
                    Projeto.$next = 2;
                    Projeto.$btnback.css("display","none");
                    Projeto.$btnnext.css("display",'block');
                    Projeto.$btnfinish.css("display",'none');
                
                    addMaskAndValidatorObj(Projeto.$form_step1);
                    addMaskAndValidatorObj(Projeto.$formplanotrabalho);
                    addMaskAndValidatorObj(Projeto.$formrepasses);
                    //
                    loadusuarios();
                    loadinstituicao();
                    loadfinanciador();
                    loadrubricas();
                    //
                    PlanoTrabalho.lista();
                    Repasse.lista();

                    try{
                        Projeto.$droparea.fileupload({
                            url:'./index/upload',
                            output:'result',
                            list:'listafiles',
                            loadurl:'./index/uploadfiles',
                            deleteurl:'./index/deletefiles'
                        });
                    }catch(e){
                        console.log('-> '+e);
                    }
                }else{
                    try{
                        if(Projeto.$orcamentogeraltemplate == null){
                            Projeto.$orcamentogeraltemplate = $('#orcamento').html();
                        }
                        $('#orcamento .row').html('Carregando...');
                        $.getJSON('./index/orcamentogeral', function(json){
                            var html = Mustache.to_html(Projeto.$orcamentogeraltemplate, json[0]);
                            $('#orcamento').html(html);
                            $('#orcamento .row').show();
                        });
                    }catch(e){
                        console.log(e);
                    }
                }
            }catch(e){
                console.log(e);
            }
        }
    };
    
    var Despesa = {
        $despesa:{},
        $rubrica:{},
        $template:null,
        $templatedetalhardespesa:null,
        $step1: $("div#formdespesa_step1"),
        $step2: $("div#formdespesa_step2"),
        $select: $("select#tiporubrica"),
        $rubricas:null,
        $listageral:null,
        $listadetalhada:null,
        $modal: $("#despesadialog"),
        
        addview:function(){
            Despesa.$step1.show();
            Despesa.$step2.hide();
            Despesa.getrubricas();
            Despesa.show();
            shortcut.remove("Backspace");
        },
        show:function(){
            showmodal(Despesa.$modal.attr("id"));
        },
        hide:function(){
            Despesa.$modal.modal('hide');
        },
        atualizardadosgerais:function(){
            try{
                $.getJSON('./index/orcamentobyprojeto?total='+Projeto.$projeto.valor+'&idprojeto='+Projeto.$projeto.idprojeto,
                function(json){
                    if(Projeto.$orcamentotemplate == null){
                        Projeto.$orcamentotemplate = $("#orcamentoprojetodetalhe").html();
                    }
                    
                    var html = Mustache.to_html(Projeto.$orcamentotemplate, json);
                    $("#orcamentoprojetodetalhe").html(html);
                });
            }catch(e){
                console.log(e);
            }
        },
        add:function(evento){
            var fieldsetCount = Despesa.$step2.children().length;
            for(var i = 1; i <= fieldsetCount; ++i){
                Despesa.$step2.children(':nth-child('+ parseInt(i) +')').find(':input:not(button)').each(function(){
                    if($(this).attr("idrubricacampo")!=undefined){
                        Despesa.$despesa[$(this).attr("idrubricacampo")] = $(this).val();
                    }
                });
            }
            console.log(Despesa.$despesa);
            
            Despesa.$despesa['idprojeto'] = Projeto.$projeto.idprojeto;
            if( $("input#repetir").val().replace(/^\s+|\s+$/, '').length==0){
                $("input#repetir").val(1);
            }
            Despesa.$despesa['repetir'] = $("input#repetir").val();
            
            $.ajax({
                type:'POST',
                data:Despesa.$despesa,
                url:'./index/inserirdespesa',
                dataType:'json',
                success: function(json){
                    Despesa.listageral();
                    Despesa.atualizardadosgerais();
                    Despesa.hide();
                }
            });  
            shortcut.add("Backspace", function() {
                Projeto.$orcamentoview.hide(0,function(){
                    Projeto.$listaview.show(0,function(){
                        Projeto.$listaprojeto.fnDraw();
                    });
                });
            });
            Despesa.hide();
            evento.preventDefault();
        },
        getrubricas:function(){
            try{
                if(Despesa.$rubricas==null){
                    $.getJSON('./index/listarubricasbyprojeto?idprojeto='+Projeto.$projeto.idprojeto, function(json){
                        Despesa.$rubricas = json;
                        Despesa.createrubricaselect();
                    }); 
                }else{
                    Despesa.createrubricaselect();
                }
            }catch(e){
                console.log('getrubricas: '+e)
            }
        },
        createrubricaselect:function(){
            var select = '<option value="">Selecione</option>';
            $.each(Despesa.$rubricas,function(key,value){
                select += '<option value="'+value['idrubrica']+'">'+value['tiporubrica']+'</option>';
            });
            Despesa.$select.html(select);
            Despesa.$select.change(function(){
                Despesa.$rubrica.idrubrica = $(this).val();
                Despesa.$step1.hide(function(){
                    Despesa.$step2.show(function(){
                        Despesa.createform();
                    });
                });
            });
        },
        createform:function(){
            try{
                $.getJSON('./index/listacamposrubrica?sEcho=0&rubrica='+Despesa.$rubrica.idrubrica, function(json){
                    if(Despesa.$template == null){
                        Despesa.$template = Despesa.$step2.html();
                    }
                    var i=0;
                    var html='';
                    html+='<div class="row-fluid">'; 
                    $.each(json["aaData"],function(key,value){
                        if(i==2){
                            html+='</div>';
                            html+='<div class="row-fluid">';
                            i=0;
                        }
                        html+='<div class="span5"> '+value['label']+' <input idrubricacampo="'+value['idrubricacampo']+'"  id="'+value['nome']+'" '+value['obrigatorio']+' mask="'+value['mask']+'" validator="'+value['validator']+'" placeholder="'+value['placeholder']+'" style="width:90%"/></div>';
                        i++;
                    });
                    html+='<div class="span4">Repetir despesa:<input id="repetir" value="1" validator="number" style="width:30%"/></div>';
                    Despesa.$step2.html(html);
                    addMaskAndValidatorObj(Despesa.$step2);
                }); 
            }catch(e){
                console.log('createform: '+e)
            }
        },
        sync_rubrica:function(){
            //sincroniza os campos
            var self = this;
            $.ajax({
                type:'POST',
                data:Despesa.$despesa,
                url:'./index/getdespesascamposbyrubrica',
                dataType:'json',
                success: function(json){
                    localStorage.setItem('lincsgp.$rubrica_campos_dados'+self.$despesa.idrubria,JSON.stringify(json));
                    self.createdetalhes();
                }
            });
        },
        createdetalhes:function(){
            try{
                var json = JSON.parse(localStorage.getItem('lincsgp.$rubrica_campos_dados'+this.$despesa.idrubria));
                var lista = $("#listadetalhada").dataTable({
                    "aaData": [],
                    "aoColumns": json['campos'],
                    "bPaginate":false,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bInfo": false,
                    "bAutoWidth": false,
                    "bStateSave": true,
                    "bDestroy":true
                });
                $('#despesageral_').hide();
                $.each(json['dados'], function(key,value){
                    lista.fnAddData(value);
                });
                $('#despesadetalhada_').show();
            }catch(err){
                console.log(err);
            }
        },
        detalhar:function(row){
            if(this.$templatedetalhardespesa == null){
                this.$templatedetalhardespesa = $('#detalhardespesa').html();
            }
            this.$despesa = this.$listageral.fnGetData()[row];
            this.createdetalhes();
            this.sync_rubrica();
            
            console.log(Despesa.$despesa); 
        },
        listageral:function(){
            try{
                //                if(Despesa.$listageral == null){
                Despesa.$listageral = $("#listadespesasgeral").dataTable({
                    "sPaginationType": "bootstrap",
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": "./index/despesageral?idprojeto="+Projeto.$projeto.idprojeto,   
                    "aoColumns": [
                        { "mData": "rubrica","bSortable":false},
                        { "mData": "total","bSortable":false},
                        { "mData": "gasto","bSortable":false},
                        { "mData": "disponivel","bSortable":false},
                        { "mData": null,"fnRender" : function(obj) {
                                return '<a href="javascript:;" onclick="Despesa.detalhar('+obj.iDataRow+')">Detalhar</a>'
                            }
                        }
                    ],
                    "bPaginate":false,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bInfo": false,
                    "bAutoWidth": false,
                    "oLanguage": {
                        "sSearch": "Buscar:",
                        "sProcessing":"Processando...",
                        "sLoadingRecords":"Carregando...",
                        "sLengthMenu":"Mostrando _MENU_ registros",
                        "sInfoFiltered": "(Filtrado de _MAX_ registros)",
                        "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                        "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sZeroRecords":"Nenhum registro encontrado",
                        "oPaginate": {
                            "sFirst": "Primeira",
                            "sLast": "Última",
                            "sNext": "Próxima",
                            "sPrevious": "Anterior"
                        }
                    },
                    "bStateSave": true,
                    "bDestroy":true
                });
                //                }else{
                //                    Despesa.$listageral.fnDraw();   
                //                }
            }catch(e){
                console.log("lista: "+e);
            }
        }
        
    };
    
    function delfiles(row){
        try{
            var d = "row="+row;
            //                console.log(obj.deleteurl);
            $.ajax({
                type:'POST',
                data:d,
                url:'./index/deletefiles',
                success: function(){
                    $("#listafiles").dataTable().fnDraw();
                }
            });
        }catch(e){
            console.log(e);
        }
    }
  
    function loadusuarios(){
		
        $('input#coordenador').autocomplete({ serviceUrl:'./index/usuariosjson',
            minChars:1, 
            delimiter: /(,|;)\s*/, 
            noCache: false, 
            zIndex: 9999,
            onSelect: function(value, data){
            }
        });
		
        $('input#coordenadortecnicos').autocomplete({ serviceUrl:'./index/usuariosjson',
            minChars:1, 
            delimiter: /(,|;)\s*/, 
            noCache: false, 
            zIndex: 9999,
            onSelect: function(value, data){ 
            }
        });
    }
    function loadinstituicao(){
        //proponente
        var sel = "";
        try{
            if(Projeto.$edit){
                sel = Projeto.$projeto.proponente;
            }
        }catch(e){
            console.log(e);
        }
        $("select#proponente").selecteditor({
            dataurl:"./index/proponentejson",
            inserturl:"./index/insertproponente",
            primarykey:"idproponente",
            placeholder:'Insira um novo Proponente',
            field:"nome",
            seleciona:sel
        });
    }
    function loadfinanciador(){
        var sel = "";
        try{
            if(Projeto.$edit){
                sel = Projeto.$projeto.financiador;
            }
        }catch(e){
            console.log(e);
        }
        //financiador
        $("select#financiador").selecteditor({
            dataurl:"./index/financiadorjson",
            inserturl:"./index/insertfinanciador",
            primarykey:"idfinanciador",
            placeholder:'Insira um novo Financiador',
            field:"nome",
            seleciona:sel
        });
		
    }
    function loadrubricas(){
        //rubrica
        $("#planotrabalho select#rubrica").selecteditor({
            dataurl:"./index/rubricajson",
            inserturl:"./index/insertrubrica",
            primarykey:"tiporubrica",
            placeholder:'Insira nova Rubrica',
            field:"tiporubrica"
        });
    }
    function showmodal(idmodal){
        $("#"+idmodal).modal({
            "backdrop"  : "static",
            "keyboard"  : true,
            "show"      : true
        });
    }
    
    $(document).ready(function(){
        Layout.load("./public/js/projeto.js", "projeto.js", "script", false, true);
        //        Layout.load("./public/js/uploaddnd.js", "uploaddnd.js", "script", true, true);
        //        Layout.load("./public/js/jquery.autocomplete.js", "jquery.autocomplete.js", "script", true, true);
        //        Layout.load("./public/js/maskvalidator.js", "maskvalidator.js", "script", true, true);
        //        Layout.load("./public/js/selecteditor.js", "selecteditor.js", "script", true, true);
        //        Layout.load("./public/js/bootstrap/bootstrap-modal.js", "bootstrap-modal.js", "script", true, true);
        Layout.load("./public/js/shortcut.js", "shortcut.js", "script", true, true);
        //        Layout.load("./public/js/jquery.dataTables.js", "jquery.dataTables.js", "script", false, true);
        Projeto.listaprojeto();
    });
</script>
