<h1 class="page-title">
    <i class="icon-home"></i>
    Usuários
</h1>
<div id="alluser">
    <select id="filtro" class="pull-right">
        <option value="">Filtrar...</option>
        <option value="0">Usuários Inativos</option>
        <option value="1">Ativos</option>
        <option value="-1">Dados Incompletos</option>
    </select>
    <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" id="listausuario" style="margin-top: -2px;">
        <thead>
            <tr>
                <th>Nome</th>
                <th>E-mail</th>
                <th>Perfil</th>
                <th>Vinculo</th>
                <th>Status</th>
<!--                <th>Laboratório</th>-->
<!--                <td align="center" style="width: 30px;" ></td>
                <td align="center" style="width: 30px;" ></td>
                <td align="center" style="width: 30px;" ></td>-->
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="8" class="dataTables_empty" align="center">Carregando...</td>
            </tr>
        </tbody>
    </table>
    <hr/>
    <div>
        <a href="#" class="btn pull-right" onclick="Usuario.activeview('alluser','convite')">Convidar novo usuário</a>
    </div>
</div>
<div id="convite" style="display: none">
    <a class="btn btn-danger" onclick="Usuario.activeview('convite','alluser');">Voltar</a>
    <hr/>
    <p>Use o campo abaixo para enviar um email para o novo usuário que deseja convidar.</p>
    <div aling="center" >
        <form onsubmit="Usuario.enviarconvite(event)" >
            <div class="row-fluid">
                <input id="nomenewuser" required="true" style="font-size: 16px; padding: 10px;width: 200px" placeholder="Digite aqui o nome do novo usuário"/>
                <input id="emailnewuser" required="true" style="font-size: 16px; padding: 10px;width: 300px" placeholder="Digite aqui o email do novo usuário"/>
                <button type="submit" class="btn btn-large" style="margin-top: -12px;">Enviar convite</button>
            </div>
        </form>
    </div>
</div>
<div id="infousuario" style="display: none;">
    <a class="btn btn-danger" onclick="Usuario.activeview('infousuario','alluser');">Voltar</a>
    <hr/>
    <div id="detalheusuario" class="row" style="margin-left:5%;display: none;">
        <div id="msgerro" class="alert alert-danger" style="display: none">
            <span></span>
        </div>
        <form id="formativarusuario" action="./" onsubmit="Usuario.ativar(event)">
            <div class="row-fluid">
                <span class="span2">
                    <div class="account-avatar">
                        <img src="https://graph.facebook.com/{{username}}/picture" alt="" class="thumbnail" />
                    </div>
                </span>
                <span class="span10">
                    <div class="row-fluid">
                        <span class="span2">
                            <strong>Nome:</strong>
                        </span>
                        <span class="span9">
                            <span >
                                {{nome}}
                            </span>
                        </span>
                    </div>
                    <div class="row-fluid">
                        <span class="span2">
                            <strong>E-mail:</strong>
                        </span>
                        <span class="span9">
                            <span >
                                {{email}}
                            </span>
                        </span>
                    </div>
                    <div class="row-fluid">
                        <span class="span2">
                            <strong>Perfil:</strong>
                        </span>
                        <span class="span9">
                            <span>
                                <select  id="perfil" required="true" style="width: 40%">
                                    <option>Carregando...</option>
                                </select>
                            </span>
                        </span>
                    </div>
                    <div class="row-fluid">
                        <span class="span2">
                            <strong>Vinculo:</strong>
                        </span>
                        <span class="span9">
                            <span>
                                <select  id="vinculo" required="true" style="width: 40%">
                                    <option>Carregando...</option>
                                </select>
                            </span>
                        </span>
                    </div>
                    <div class="row-fluid">
                        <span class="span2">
                            <strong>Laboratório:</strong>
                        </span>
                        <span class="span9">

                            <span>
                                <select id="laboratorios" required="true" style="width: 40%">
                                    <option>Carregando...</option>
                                </select>
                            </span>
                        </span>
                    </div>
                </span>
            </div>
            <hr/>
            <div class="row-fluid">
                <button type="reset"  class="btn btn-danger pull-right" onclick="Usuario.activeview('infousuario','alluser');">Cancelar</button>
                <button type="submit" class="btn btn-primary pull-right" style="margin-right: 10px;">Ativar usuário</button>
            </div>
        </form>
    </div>
</div>
<script src="./public/js/jquery.dataTables.js"></script>
<script src="./public/js/selecteditor.js"></script>

<script>
    //    var listausuario = null;
    //    var templatedetalhe = null;
    //    actionlistausuario();
    //    getuserinfo();
    var Usuario = {
        $usuario:{},
        $lista:null,
        $templatedetalhe:null,
        $alluser:$("#alluser"),
        $infousuario:$("#infousuario"),
        $select_laboratorios:$("#detalheusuario select#laboratorios"),
        $select_vinculo:$("#detalheusuario select#vinculo"),
        $select_perfil:$("#detalheusuario select#perfil"),
        
        init:function(){
            
            Usuario.lista();
            $("#alluser select#filtro").change(function(){
                Usuario.$lista.fnFilter($(this).val(),0,false,false);
            });
        },
        atualizar:function(){
            if(Usuario.$lista==null){
                Usuario.lista();
            }else{
                Usuario.$lista.fnDraw();
            }  
        },
        ativar:function(evento){
            try{
                Usuario.$usuario.perfil = $("#formativarusuario select#perfil").val();
                Usuario.$usuario.vinculo_idvinculo = $("#formativarusuario select#vinculo").val();
                Usuario.$usuario.laboratorio_idlaboratorio = $("#formativarusuario select#laboratorios").val();
                $.ajax({
                    type:'POST',
                    data:Usuario.$usuario,
                    url:'./index/updateusuarios',
                    dataType:'json',
                    success: function(json){
                        if(json['status']=='sucesso'){
                            Usuario.activeview('infousuario','alluser');
                            Usuario.atualizar();
                            Layout.getuserinfo();
                        }else{
                            $("#msgerro > span").html("Ops! Ocorreu um erro: "+json['erro']);
                            $("#msgerro").show();
                        }
                    }
                });
            }catch(e){
                console.log(e);
            }
            evento.preventDefault();
        },
        ativarview:function(row){
            try{
                Usuario.$usuario = Usuario.$lista.fnGetData()[row];
                console.log(Usuario.$usuario);
                Usuario.$alluser.hide(0,function(){
                    Usuario.$infousuario.show(0,function(){
                        
                        if(Usuario.$templatedetalhe==null){
                            Usuario.$templatedetalhe = $('#detalheusuario').html();
                        }
                        
                        var html = Mustache.to_html(Usuario.$templatedetalhe, Usuario.$usuario);
                        $('#detalheusuario').html(html);
                        
                        Usuario.loadlaboratorios();
                        Usuario.loadvinculo();
                        Usuario.loadperfil();
                        $('#detalheusuario').show();
                    });
                });
            }catch(e){
                console.log('ativarview: '+e);
            }
        },
        lista:function(){
            try{
                Usuario.$lista = $('#listausuario').dataTable({
                    "sPaginationType": "bootstrap",
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": "./index/usuariolist",   
                    "aoColumns": [
                        { "mData": "nome"},
                        { "mData": "email"},
                        { "mData": "perfil"},
                        { "mData": "vinculo"},
                        { "mData": null,"fnRender" : function(obj) {
                                var status = obj.aData.status;
                                if(status == 1){
                                    return '<span style="color:green">Ativo</span>';
                                }else{
                                    return '<span ><a href="#" style="color:red" onclick="Usuario.ativarview('+obj.iDataRow+')">Ativar</a></span>';
                                }
                            }
                        }
                    ],
                    "bPaginate":true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bInfo": false,
                    "bAutoWidth": false,
                    "oLanguage": {
                        "sSearch": "Buscar:",
                        "sProcessing":"Processando...",
                        "sLoadingRecords":"Carregando...",
                        "sLengthMenu":"Mostrando _MENU_ registros",
                        "sInfoFiltered": "(Filtrado de _MAX_ registros)",
                        "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                        "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sZeroRecords":"Nenhum registro encontrado",
                        "oPaginate": {
                            "sFirst": "Primeira",
                            "sLast": "Última",
                            "sNext": "Próxima",
                            "sPrevious": "Anterior"
                        }
			
                    }
                });  
            }catch(e){
                console.log(e);
            }
        },
        loadlaboratorios:function(){
            //rubrica
            $("#detalheusuario select#laboratorios").selecteditor({
                dataurl:"./index/laboratoriojson",
                inserturl:"./index/insertlaboratorio",
                primarykey:"idlaboratorio",
                placeholder:'Insira um novo laboratório',
                field:"laboratorio",
                seleciona:Usuario.$usuario.laboratorio_idlaboratorio
            });
        },
        loadvinculo:function(){
            //rubrica
            $("#detalheusuario select#vinculo").selecteditor({
                dataurl:"./index/vinculojson",
                inserturl:"./index/insertvinculo",
                primarykey:"idvinculo",
                placeholder:'Insira um novo Vinculo',
                field:"vinculo",
                seleciona:Usuario.$usuario.vinculo_idvinculo
            });
        },
        loadperfil:function(){
            //rubrica
            if(Usuario.$usuario.perfil == "Membro"){
                $("#detalheusuario select#perfil").append('<option value="Membro" selected >Membro</option>');
                $("#detalheusuario select#perfil").append('<option value="Coordenador" >Coordenador</option>');
                $("#detalheusuario select#perfil").append('<option value="Administrador" >Administrador</option>');
            }else if(Usuario.$usuario.perfil == "Coordenador"){
                $("#detalheusuario select#perfil").append('<option value="Membro" >Membro</option>');
                $("#detalheusuario select#perfil").append('<option value="Coordenador" selected>Coordenador</option>');
                $("#detalheusuario select#perfil").append('<option value="Administrador" >Administrador</option>');
            }else{
                $("#detalheusuario select#perfil").append('<option value="Membro" >Membro</option>');
                $("#detalheusuario select#perfil").append('<option value="Coordenador" >Coordenador</option>');
                $("#detalheusuario select#perfil").append('<option value="Administrador" selected>Administrador</option>');
            }
        },
        activeview:function(current,_new){
            $("#"+current).hide(0,function(){
                $("#"+_new).show(0,function(){
                });
            });
        },
        enviarconvite:function(){
        
        }
    };
    
    $(document).ready(function(){
        Layout.load("./public/js/jquery.dataTables.js", "jquery.dataTables.js", "script", true, true);
        Layout.load("./public/js/selecteditor.js", "selecteditor.js", "script", true, true);
        Usuario.init();
    });
    
</script>